Update agent.rb
net-ssh/net-ssh pull request #799
Opened 2021-02-16 15:59 UTC by Fguhhla

Add excetion handle to read_paket because of the following error while using net-ssh 6.1 with test-kitchen 

from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:211:in read_packet' /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:147:in append': can't modify frozen String: "" (FrozenError)

2021-02-16 16:26 UTC, mfazekas commented
@Fguhhla thanks much for the PR, I'd be more interested in the reason for the crash vs such a workaround, first it silences errors, second it prints to stdout which might not be appropriate for all apps.

2021-02-16 16:28 UTC, mfazekas commented
Isn't it possible that the code was ran In all strings frozen mode?! 
RUBYOPT="--enable-frozen-string-literal"

2021-02-16 17:15 UTC, fwininger requested changes

2021-02-16 17:15 UTC, fwininger commented on lib/net/ssh/authentication/agent.rb
> +            puts e.message
Ignore StandardError here is a very bad choice.

2021-03-12 19:38 UTC, tas50 commented
@mfazekas We freeze strings throughout Test Kitchen

2021-03-14 05:36 UTC, mfazekas commented
@tas50 can you elaborate?! Do you use `enable-frozen-string-literal` globally ?!  `net-ssh` doesn't support this at the moment. [Buffer](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/buffer.rb) for sure is not frozen literal compatible.

2021-03-14 05:59 UTC, tas50 commented
You know it looks like we're not actually doing it in 100% of the files like I thought. We do set the frozen string literal magic comment in a large number of the Test Kitchen files though since it has a nice memory impact and at one point the world was prepping for that as the default in Ruby 3.

2021-03-15 07:01 UTC, mfazekas commented
@Fguhhla thanks much for the PR. We'd need to understand why this error happens, just silencing it is not solution. 

I'm closing this PR, let us know if you have more background info on this.

2021-03-15 07:01 UTC, closed without merging